FROM ubuntu:16.04

ENV PATH=$PATH:$HOME/bin

WORKDIR ~/
RUN apt-get update && apt-get install -y software-properties-common

RUN add-apt-repository -y ppa:scipy/ppa

RUN apt-get install -y \
    python \
    python-numpy \
    python-scipy \
    python-pip \
    zlib1g-dev \
    git \
    wget \
    libncurses5-dev \
    libbz2-dev \
    liblzma-dev \
    pkg-config \
    automake \
    autoconf \
    glib-2.0-dev \
    unzip

RUN pip install cython
RUN pip install pysam

RUN mkdir $HOME/bin

RUN git clone https://github.com/samtools/htslib.git
RUN make -C htslib

RUN git clone https://github.com/samtools/samtools.git
RUN make -C samtools
RUN cp samtools/samtools $HOME/bin
RUN cp samtools/misc/wgsim $HOME/bin

RUN git clone https://github.com/samtools/bcftools.git
RUN make -C bcftools
RUN cp bcftools/bcftools $HOME/bin


CMD []



